config/routes.rb
Rails.application.routes.draw do
  #get 'grid_cells/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'grid_cells#index'
  post '/grid_cells/update_cell'
	get '/grid_cells/reload_cells'
	get '/grid_cells/leader_board'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cell.rb
class Cell < ApplicationRecord
  belongs_to :user

  validates :color_code,:row,:column, presence: true

  def self.find_color_code_and_user_stamp(x,y)
    result = []
    palette = Cell.where(row: x,column: y).last
    result = [palette.color_code,"#{palette.user.user_name} #{palette.form_time_stamp}"] if palette.present?
    result
  end

  def form_time_stamp
    self.updated_at.strftime("%d-%m-%Y %H:%M:%S")
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :cells,dependent: :destroy
  validates :user_name,:remote_ip, presence: true

  scope :get_palette_count, -> { joins(:cells).select("users.*, count(cells.id) as color_count").group("users.id").order("color_count DESC") }
  

  def mostly_used_color
   self.cells.group(:color_code).count.sort {|a1,a2| a2[1]<=>a1[1]}.first[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/grid_cells_controller.rb
class GridCellsController < ApplicationController
  before_action :find_or_create_user

  def index
  end

  def update_cell
    params.permit!
    params[:cells].split(",").each do |cell|
      position = cell.split("-")[1].split("_")
      @user.cells.create(color_code: params[:color_code],row: position[0],column: position[1])
    end
    respond_to do |format|
      format.js { flash.now[:notice] = "Color updated successfully" }
    end
  end

  def reload_tiles
    respond_to :js
  end

  def leader_board
    @users = User.get_palette_count
  end

  protected

  def find_or_create_user
    user = User.where(remote_ip: request.remote_ip).last
    if user.present?
      @user = user
    else
      username = Faker::Name.unique.name
      @user = User.create(user_name: username,remote_ip: request.remote_ip)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def get_tile_details(row,col)
    Cell.find_color_code_and_user_stamp(row,col)
  end

  def generate_cell(row,col)
    tile_info = get_tile_details(row,col)
    raw("<div onclick='toggleClass(this);' class='content' 
         id='tile-#{row}_#{col}' #{style_attributes(tile_info)}></div>")
  end

  def style_attributes(tile_info)
    "style='background-color: #{tile_info[0]}' title='#{tile_info[1]}'"
  end

end

app/helpers/grid_cells_helper.rb
module GridCellsHelper
end

app/views/grid_cells/_cells.html.erb
<table id="palette-table" class="table table-bordered">
  <%for row in 1..20 do %>
   <tr>
    <% for col in 1..20 do%>
      <td> <%= generate_cell(row,col)%></td>
    <%end%>
   </tr>
  <%end%>
</table>

app/views/grid_cells/_success.html.erb
<div class="alert alert-success alert-dismissible"">
	<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <strong><%= notice %></strong>
</div>

app/views/grid_cells/index.html.erb
<div id="tiles" class='row'>
  <%= render partial: "cells"%>
</div>
<br/>
<div class="form-group">
  Color Picker: <input class="colors form-control">
</div>
<div class="form-group">
  <button class="btn btn-primary" onclick="updateTileColors();">Ok</button>
  <button class="btn btn btn-warning">Cancel</button>
</div>

app/views/grid_cells/leader_board.html.erb
<table class="table table-striped">
  <thead>
   <tr>
    <td>S.No</td>
    <td>Username</td>
    <td>Colors Placed</td>
    <td>Favourite Color</td>
   </tr>
  </thead>
  <tbody>
   <%@users.each_with_index do |user,index|%>
    <tr>
     <td><%= index+=1%>.</td>
     <td><%= user.user_name%></td>
     <td><%= user.color_count%></td>
     <td style="background-color: <%= user.mostly_used_color%>; width: 10px"></td>
    </tr>
   <%end%>
  </tbody>
</table>

app/views/grid_cells/reload_cells.js.erb
$('#tiles').html("<%= escape_javascript render(:partial => 'grid_cells/cells') %>");

app/views/grid_cells/update_cell.js.erb
$("div.selected").removeClass("selected");
$("#flash").html('<%= j render partial: "grid_cells/success" %>');

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Sample Palette App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <li><%= link_to 'CellsPalette', root_path, class: "nav-link" %></li>
      </li>
      <li class="nav-item">
        <li><%= link_to 'LeaderBoard', grid_cells_leader_board_path , class: "nav-link" %></li>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'CellsPalette', root_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SamplePalette</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div id="flash">
      <% if notice.present? %>
        <%= render partial: "grid_cells/success" %>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>